homepage: "https://github.com/ruddro-roy/sindook"
language: go
main_repo: "https://github.com/ruddro-roy/sindook"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
primary_contact: "roy@ruddro.com"
