name: ClusterFuzzLite batch fuzzing
on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:
permissions: read-all
jobs:
  batch-fuzzing:
    runs-on: ubuntu-latest
    steps:
      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: go
          sanitizer: address
      - name: Run fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 1800
          mode: batch
          sanitizer: address
